### ISSUE TITLE
file explorer

### ISSUE THREAD

**Issue by etuke68** [cttynul/edge-adblock#2]
After using the adblock for a few days my computer wont open the file explorer tab to view files on my computer,also AVG free will not open.When I try to restart it will just sit there saying restarting and not go any further.I have to do a hard reboot.I really like the program and would want to continue using it but just wanted to let it known of the issue i'm having and see if there is a solution.I'm new to this so I hope I'm posting this in the correct area.

**Comment by cttynul** [comment]
If you disable Edge Adblock will your computer be back "usable"? You can just rerun .bat as admin and select disable option.
Edge Adblock is just a remirroring of ads website, it shouldnt meddle with your software.

**Comment by etuke68** [comment]
Once i have the problem i tried to disable but it wont respond.Im thinking its because of file explorer wont open and thats where the program is located.i tried puttingbit on desktop but it still wont respond.when its under downloads i cant even get to it.

Sent from my Samsung device over Bell's LTE network.

-------- Original message --------

**Comment by etuke68** [comment]
I should note that the computer works fine when enabled,this happens over a period of time,not sure what triggers it and not 100% sure its ad blocker.This only started happening when I used ad blocker so I'm assuming its whats causing it.AVG free wouldn't open also when this happened,maybe its connected.Thanks for the prompt reply.

**Comment by cttynul** [comment]
Edge Adblock just evoids your PC accessing some ads websites and it flushes DNS cache, I think that's not its fault.
I would suggest you to try running your PC into safe mode (pressing f8 or shift at boot) download MalwareBytes and perform a scan.

**Comment by etuke68** [comment]
Adblock has been disabled for 5 days and the problem didn't happen since,going to  run it again now and see if it comes back.

**Comment by cttynul** [comment]
Keep me update if your problem will come back.

**Comment by etuke68** [comment]
Been running it for 8 days now and it hasn't shown back up.I would put up with a little glitch every week or so just to get rid of online adds.

**Comment by etuke68** [comment]
happy to say its been 2 months and haven't had any issues since,don't really know why it was happening but it cleared itself up.I have since installed it on my other computers and is working fine,this program is like a God send for PC users highly recommend it.
