### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by JeremyWW** [cttynul/edge-adblock#3]
Hi,

Thanks for this. Just some questions if I may:

1) On this site - http://www.chris123nt.com/2015/05/05/blocking-ads-with-microsoft-edge-project-spartan/ there are some instructions for using a hosts file solution which includes something your regfile doesn't have - Creating a new DWORD named “MaxNegativeCacheTtl” and setting it to 0. Is that not necessary?

2) How do we keep the hosts file up to date? Do we wait for a new release from you?

Thanks

**Comment by cttynul** [comment]
1) Flushing client cache is not strictly necessary, but I will add that as soon as. Thank you!
2) Disabling and reenabling Adblock, everytime you run .bat script it will download the most updated hosts file provided by Dan Pollock.
